service: notification-query

provider:
  name: aws
  runtime: java8
  timeout: 90

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource:
        - "Fn::Join":
          - ":"
          -
            - "arn:aws:logs"
            - Ref: "AWS::Region"
            - Ref: "AWS::AccountId"
            - "log-group:/aws/lambda/*:*:*"
    - Effect: "Allow"
      Action:
        - "sns:ListTopics"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - "Fn::Join":
          - ":"
          -
            - "arn:aws:sns"
            - Ref: "AWS::Region"
            - "*"
            - "*"
package:
  artifact: target/notification-query-1.0.0-aws.jar

functions:
  notify:
    handler: config.Handler
    events:
      - schedule:
          rate: cron(0 16 * * ? *)
    vpc:
      securityGroupIds:
        - sg-xxxxxxxx
      subnetIds:
        - subnet-xxxxxxxx
    environment: 
      REGION: ${opt:region}
      RDS_ENDPOINT: xxxx.rds.amazonaws.com
      RDS_DATABESNAME: xxxx
      RDS_USERNAME: xxxx
      RDS_PASSWORD: xxxx
      SNS_TOPIC: notification-query-xxxx
      SNS_SUBJECT: "Notification Query Results"